### ISSUE TITLE
Incorrect work with cirillyc alphabet in insert_upload_job

### ISSUE THREAD

**Issue by selesnow** [rstats-db/bigrquery#112] opened 2016-04-14 12:47 UTC
Hello!

I have data frame which contains cirillyc characters, and when i use insert_upload_job and this characters incorect load into google big query.

```
insert_upload_job(project, dataset, table, values, billing = project,
                  create_disposition = "CREATE_IF_NEEDED",
                  write_disposition = "WRITE_APPEND")
```

<img src="http://img.netpeak.ua/alsey/146064887541_kiss_112kb.jpg" data-canonical-src="http://img.netpeak.ua/alsey/146064887541_kiss_112kb.jpg" style="max-width:100%;">
How i can load Cirillyc character into google big query?
http://img.netpeak.ua/alsey/146064887541_kiss_112kb.jpg
`Sys.info()`
 sysname        release        version       nodename        machine          login           user effective_user 
     "Windows"     ">= 8 x64"   "build 9200"        "ALSEY"       "x86-64"        "Alsey"        "Alsey"        "Alsey" 

`sessionInfo()`
R version 3.2.4 (2016-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251    LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C  
[5] LC_TIME=Russian_Russia.1251    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bigrquery_0.2.0

loaded via a namespace (and not attached):
 [1] httr_1.1.0             RGoogleAnalytics_0.1.1 assertthat_0.1         magrittr_1.5           R6_2.1.2               parallel_3.2.4  
 [7] DBI_0.3.1              tools_3.2.4            dplyr_0.4.3            curl_0.9.6             Rcpp_0.12.4            lubridate_1.5.0  
[13] stringi_0.5-5          jsonlite_0.9.19        stringr_1.0.0          openssl_0.9.2

**Comment by BrianWeinstein** [comment] 2016-04-15 14:03
I think this is a limitation of BigQuery itself, not the R package. Do the characters render properly if you try uploading via the web UI?

From the [API documentation](https://cloud.google.com/bigquery/docs/reference/v2/jobs#configuration.load.encoding), the default character encoding for upload is UTF-8 . The only other option is ISO-8859-1, but the cyrillic alphabet is part of the ISO-8859-5 character set.

Regardless, bigrquery doesn't support the `configuration.load.encoding` argument yet, but I believe we'd have to add it [here](https://github.com/rstats-db/bigrquery/blob/master/R/upload.r#L43-L45) (and add the proper arguments to the function.

**Comment by selesnow** [comment] 2016-04-15 14:17
I founed solution, before send data frame into bigquery data frame must encoding two times to UTF8.

I write this function, maybe you can add this function to bigrquery packege's function?

```
beforeSendEnc <- function(dataframe) {
  for(i in 1:length(dataframe)) {
    if(class(dataframe[,i]) %in% c("character","factor")) {
      dataframe[,i] <- lapply(dataframe[,i], function(x) {iconv(x, to = "UTF8");iconv(x, to = "UTF8")})}
  }
  dataframe <- as.data.frame(dataframe)
}
```

**Comment by hadley** [comment] 2017-04-18 16:16
Duplicate of #45

**Closed by hadley** 2017-04-18 16:16 UTC
