### ISSUE TITLE
seems like datetime is not supported now

### ISSUE THREAD

**Issue by inkrement** [rstats-db/bigrquery#140] opened 2017-01-26 23:20 UTC
I don't know if this is a dplyr problem or bigrquery, but it is not possible to work with datetime-fields

```
tbl(src_bigquery("someproject", "dataset"), "tablewithdatetimefield")
```

> Error: Don't know how to convert type datetime

**Comment by kmatt** [comment] 2017-01-27 03:25
https://github.com/rstats-db/bigrquery/pull/129

**Comment by inkrement** [comment] 2017-01-27 11:35
Oh, thanks for the pull request! I tried to install it like this:

```
devtools::install_github("rstats-db/bigrquery#129", force= TRUE)
```

But I still get the same error. Did I forget something?

**Comment by hadley** [comment] 2017-04-18 13:18
Duplicate of #128

**Closed by hadley** 2017-04-18 13:18 UTC
