### ISSUE TITLE
list_tables() returns a maximum of 1000 table names

### ISSUE THREAD

**Issue by TroyHernandez** [rstats-db/bigrquery#58] opened 2015-07-30 19:35 UTC
`length(list_tables(project, dataset, max_results = 1001))`
`[1] 1000`

I have over 3000 tables in the dataset and could really use all of their names.

**Comment by craigcitro** [comment] 2015-07-30 19:51
so the BQ API has a limit on how many results it will return. 
* for bigrquery, we should definitely handle that paging ourselves -- i'm going to assume that's what you wanted here.
* that said, if you need something right now as a workaround, you could fish out the pagetoken and include it on the next request, and it'd let you pull the next 1000 tables. (and, of course, repeat as necessary)

from past experience, the slick thing to do here is to fetch lazily, which we should make sure we do.

**Comment by TroyHernandez** [comment] 2015-07-30 20:30
I'm not sure what `bq_get()` does, but it looks like it's getting more than just the names.  Right now I'm doing this as a workaround:

`length(system("bq ls --max_results=1001 project:dataset", intern = TRUE))`
`[1] 1001`

**Comment by hadley** [comment] 2017-04-18 13:15
@craigcitro do you know of any big public datasets that we could use for testing here?

**Comment by craigcitro** [comment] 2017-04-19 05:09
@hadley I think the easier approach is to expose the param that controls number of items per API call (either as a param or just for tests), and then just set that to 1 and try something with at least 2 items.

**Comment by hadley** [comment] 2017-04-19 12:02
Oh, duh, yeah.

**Comment by hadley** [comment] 2017-04-19 16:19
Duplicate of #108

**Closed by hadley** 2017-04-19 16:19 UTC
Labels: bug

**Comment by TroyHernandez** [comment] 2017-04-22 16:30
A little late to this... and it was two jobs ago, but IIRC bq_get() for this large number of tables was super slow because it was returning a bunch of additional unnecessary info... just a warning.

**Comment by craigcitro** [comment] 2017-04-22 16:53
Good call @TroyHernandez -- just filed #153 for that.
